### ISSUE TITLE
TypeMappingException: Type io.leangen.graphql.spqr.spring.autoconfigure.DefaultGlobalContext is unbounded or missing generic type parameters

### ISSUE THREAD

**Issue by csueiras** [leangen/graphql-spqr-spring-boot-starter#29]
Hi I believe I found a bug, whenever the DefaultGlobalContext is injected without the type being specified for the request object a TypeMappingException is raised:

```
Caused by: io.leangen.graphql.metadata.exceptions.TypeMappingException: Type io.leangen.graphql.spqr.spring.autoconfigure.DefaultGlobalContext is unbounded or missing generic type parameters
	at io.leangen.graphql.util.ClassUtils.completeGenerics(ClassUtils.java:509) ~[spqr-0.9.9.jar:na]
	at io.leangen.graphql.metadata.strategy.type.DefaultTypeTransformer.transform(DefaultTypeTransformer.java:28) ~[spqr-0.9.9.jar:na]
	at io.leangen.graphql.metadata.strategy.query.AnnotatedArgumentBuilder.buildResolverArguments(AnnotatedArgumentBuilder.java:40) ~[spqr-0.9.9.jar:na]
	... 65 common frames omitted
```

Here's an example to reproduce:

```@GraphQLApi
@Service
public class SpqrBugService {
    @GraphQLNonNull
    @GraphQLQuery(name = "coolPeople")
    public List<String> findCoolPeople(@GraphQLArgument(name = "coolnessFactor") final int factor,
                                       @GraphQLRootContext final DefaultGlobalContext ctx) {

        if (factor > 5) {
            return ImmutableList.of("Me");
        }

        return ImmutableList.of();
    }
}```

A workaround is to do: 
```
@GraphQLRootContext final DefaultGlobalContext<Object> ctx
```

graphql-spqr version 0.9.9
graphql-spqr-spring-boot-starter 0.0.4

**Comment by csueiras** [comment]
I thought about this some more, the issue is that if you are in the context of a subscription the DefaultGlobalContext's type would be WebSocketSession but if it's in the context of a query then you would get HttpServletRequest, which is why I am not providing the type (I'm pretty sure I saw an example @kaqqao provided somewhere without the type specified). Maybe a fix for this is to either relax the type checking thats going on or perhaps a bit better is to remove the generic typing from the DefaultGlobalContext and use turn the getNativeRequest into a generic method that will cast to whatever the specialized type should be?

I'll donate a PR for this if this approach sounds good @kaqqao ?
